@baseUrl = http://localhost:5001
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
withCredentials: true

{
  "username": "quan0401",
  "password": "quan0401"
}
