@baseUrl = http://localhost:5001
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/follower/add/64d7176700dd5991fa36e90e
Content-Type: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/follower/unfollow/64d7176700dd5991fa36e90e
Content-Type: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/follower/64d7176700dd5991fa36e90e
Content-Type: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/follower/block/64d1d8eeffde0ce3a2bbd12d/64d7176700dd5991fa36e90e
Content-Type: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/follower/unblock/64d1d8eeffde0ce3a2bbd12d/64d7176700dd5991fa36e90e
Content-Type: application/json
withCredentials: true

