@baseUrl = http://localhost:5001
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "1234",
  "bgColor": "1234",
  "privacy": "1234",
  "gifUrl": "1234",
  "profilePicture": "1234",
  "feelings": "1234",
}

