@baseUrl = http://localhost:5001
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/reaction
Content-Type: application/json
withCredentials: true

{
  "userTo": "64d1d8eeffde0ce3a2bbd12d",
  "type": "like",
  "postId": "64d3615382e9d766c93d9aa5",
  "profilePicture": "https://res.cloudinary.com/vdg3fsapzu/image/upload/1691474164/social/64d1d8eeffde0ce3a2bbd12d.jpg",
  "postReactions": {
    "like": 1,
    "love": 0,
    "haha": 0,
    "wow": 0,
    "sad": 0,
    "angry": 0
  },
  "previousReaction": "sad"
}

